import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs"
import { ThemeProvider } from "@/providers/ThemeProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300","500","700","900"]
});

export const metadata: Metadata = {
  title: "AspireAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <ThemeProvider attribute={"class"} defaultTheme="light" enableSystem disableTransitionOnChange>
            <Navbar />
            {children}  
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
